version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-warlocks
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production